import type { Metadata } from 'next';
import './globals.scss';
import '@/styles/_colors.scss';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@/context/ThemeContext';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body data-theme="light-mode" className={`${roboto.className}`}>
          {children}
          <div id="modal"></div>
        </body>
      </ThemeProvider>
    </html>
  );
}
